server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: scdemo
    password: scdemopass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false